<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Options for file formats • harpIO</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Options for file formats">
<meta property="og:description" content="harpIO">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">harpIO</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9176</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/file_options.html">Options for file formats</a>
    </li>
    <li>
      <a href="../articles/read_raw_forecast.html">Reading forecast model data</a>
    </li>
    <li>
      <a href="../articles/transformations.html">Transforming forecast model data</a>
    </li>
    <li>
      <a href="../articles/write_forecast_data.html">Writing forecast model data</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/harphub/harpIO/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="file_options_files/accessible-code-block-0.0.1/empty-anchor.js"></script><link href="file_options_files/anchor-sections-1.0/anchor-sections.css" rel="stylesheet">
<script src="file_options_files/anchor-sections-1.0/anchor-sections.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Options for file formats</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/harphub/harpIO/blob/master/vignettes/file_options.Rmd"><code>vignettes/file_options.Rmd</code></a></small>
      <div class="hidden name"><code>file_options.Rmd</code></div>

    </div>

    
    
<p>For this vignette, we will use the {harpIO} and {dplyr} packages. Note that {dplyr} is only used for the <code><a href="https://dplyr.tidyverse.org/reference/select.html">dplyr::select()</a></code> function to remove some columns from data frames so that they are not too wide for the vignette!</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">harpIO</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">dplyr</span>)</pre></body></html></div>
<p>{harpIO} is able to read data from several different file formats. This is includes grib (both editions 1 and 2), netcdf, FA and vfld / vobs. In most cases, reading forecast data with the <code><a href="../reference/read_forecast.html">read_forecast()</a></code> function is straightforward, but there are some issues that need to be taken into account for some formats. This vignette describes the extra options for grib and netcdf file formats.</p>
<div id="grib-files" class="section level2">
<h2 class="hasAnchor">
<a href="#grib-files" class="anchor"></a>Grib files</h2>
<p>Grib files have long been used to store meteorological data. They are a binary data format and store “messages” as 2d fields. Each message is accompanied by metadata that describe the geographic projection of the data and the grid that they are on. This metadata also includes key-value pairs that describe what the data are - i.e. the parameter, what vertical level they are on, etc. {harpIO} harnesses the {Rgrib2} package to read data from grib files, making use of the key-value pairs to extract the correct 2d fields from the files. Behind the scenes, {Rgirb2} uses the <a href="https://confluence.ecmwf.int/display/ECC/ecCodes+Home">ecCodes</a> system library, which includes lookup tables for many different operational centres.</p>
<p>For built in harp parameters (see <code><a href="../reference/show_harp_parameters.html">show_harp_parameters()</a></code>), the extraction of grib messages is done based on the grib <em>shortName</em>, <em>indicatorOfTypeOfLevel</em>, <em>level</em>, <em>dataDate</em>, <em>dataTime</em> and <em>stepRange</em> keys. Additionally, for ensemble forecasts the <em>perturbationNumber</em> key is used when different ensemble members are in the same file. In some cases, the values used for these keys may not be compatible with the key-value pairs used in some grib files. For example, different forecast centres may use values for the shortName key that are not listed in the lookup tables that are included with ecCodes, or store fields on vertical levels that are not consistent with what {harpIO} expects. In order to address the <code><a href="../reference/grib_opts.html">grib_opts()</a></code> function can be used to set the <code>file_format_opts</code> argument in calls to <code><a href="../reference/read_forecast.html">read_forecast()</a></code> or <code><a href="../reference/read_grid.html">read_grid()</a></code> so that specific key-value pairs can be used to override those built in to {harpIO}.</p>
<p>In the following examples, we will use <code><a href="../reference/read_grid.html">read_grid()</a></code> to read gridded data from a grib file in the {harpData} package, so first we create the path to the file. We export this to a system variable so that</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="no">grib_file</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/system.file.html">system.file</a></span>(
  <span class="st">"grib/AROME_Arctic/2018/07/10/00/fc2018071000+006grib_fp"</span>,
  <span class="kw">package</span> <span class="kw">=</span> <span class="st">"harpData"</span>
)</pre></body></html></div>
<p>We can then use the system command, <code>grib_ls</code> from ecCodes to get a summary of the content of the grib file. The -p tag is used to just select the keys we might be interested in.</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/system.html">system</a></span>(
  <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(
    <span class="st">"grib_ls"</span>,
    <span class="st">"-p shortName,indicatorOfParameter,typeOfLevel,level"</span>,
    <span class="no">grib_file</span>
  )
)</pre></body></html></div>
<pre><code>#&gt; shortName             indicatorOfParameter  typeOfLevel           level                 
#&gt; t                     11                    heightAboveGround     0                    
#&gt; z                     6                     heightAboveGround     0                    
#&gt; t                     11                    heightAboveGround     2                    
#&gt; q                     51                    heightAboveGround     2                    
#&gt; u                     33                    heightAboveGround     10                   
#&gt; v                     34                    heightAboveGround     10                   
#&gt; tcc                   71                    heightAboveGround     0                    
#&gt; u                     33                    isobaricInhPa         50                   
#&gt; u                     33                    isobaricInhPa         100                  
#&gt; u                     33                    isobaricInhPa         150                  
#&gt; u                     33                    isobaricInhPa         200                  
#&gt; u                     33                    isobaricInhPa         250                  
#&gt; u                     33                    isobaricInhPa         300                  
#&gt; u                     33                    isobaricInhPa         400                  
#&gt; u                     33                    isobaricInhPa         500                  
#&gt; u                     33                    isobaricInhPa         600                  
#&gt; u                     33                    isobaricInhPa         700                  
#&gt; u                     33                    isobaricInhPa         800                  
#&gt; u                     33                    isobaricInhPa         850                  
#&gt; u                     33                    isobaricInhPa         900                  
#&gt; u                     33                    isobaricInhPa         925                  
#&gt; u                     33                    isobaricInhPa         950                  
#&gt; u                     33                    isobaricInhPa         1000                 
#&gt; v                     34                    isobaricInhPa         50                   
#&gt; v                     34                    isobaricInhPa         100                  
#&gt; v                     34                    isobaricInhPa         150                  
#&gt; v                     34                    isobaricInhPa         200                  
#&gt; v                     34                    isobaricInhPa         250                  
#&gt; v                     34                    isobaricInhPa         300                  
#&gt; v                     34                    isobaricInhPa         400                  
#&gt; v                     34                    isobaricInhPa         500                  
#&gt; v                     34                    isobaricInhPa         600                  
#&gt; v                     34                    isobaricInhPa         700                  
#&gt; v                     34                    isobaricInhPa         800                  
#&gt; v                     34                    isobaricInhPa         850                  
#&gt; v                     34                    isobaricInhPa         900                  
#&gt; v                     34                    isobaricInhPa         925                  
#&gt; v                     34                    isobaricInhPa         950                  
#&gt; v                     34                    isobaricInhPa         1000                 
#&gt; t                     11                    isobaricInhPa         50                   
#&gt; t                     11                    isobaricInhPa         100                  
#&gt; t                     11                    isobaricInhPa         150                  
#&gt; t                     11                    isobaricInhPa         200                  
#&gt; t                     11                    isobaricInhPa         250                  
#&gt; t                     11                    isobaricInhPa         300                  
#&gt; t                     11                    isobaricInhPa         400                  
#&gt; t                     11                    isobaricInhPa         500                  
#&gt; t                     11                    isobaricInhPa         600                  
#&gt; t                     11                    isobaricInhPa         700                  
#&gt; t                     11                    isobaricInhPa         800                  
#&gt; t                     11                    isobaricInhPa         850                  
#&gt; t                     11                    isobaricInhPa         900                  
#&gt; t                     11                    isobaricInhPa         925                  
#&gt; t                     11                    isobaricInhPa         950                  
#&gt; t                     11                    isobaricInhPa         1000                 
#&gt; q                     51                    isobaricInhPa         50                   
#&gt; q                     51                    isobaricInhPa         100                  
#&gt; q                     51                    isobaricInhPa         150                  
#&gt; q                     51                    isobaricInhPa         200                  
#&gt; q                     51                    isobaricInhPa         250                  
#&gt; q                     51                    isobaricInhPa         300                  
#&gt; q                     51                    isobaricInhPa         400                  
#&gt; q                     51                    isobaricInhPa         500                  
#&gt; q                     51                    isobaricInhPa         600                  
#&gt; q                     51                    isobaricInhPa         700                  
#&gt; q                     51                    isobaricInhPa         800                  
#&gt; q                     51                    isobaricInhPa         850                  
#&gt; q                     51                    isobaricInhPa         900                  
#&gt; q                     51                    isobaricInhPa         925                  
#&gt; q                     51                    isobaricInhPa         950                  
#&gt; q                     51                    isobaricInhPa         1000                 
#&gt; z                     6                     isobaricInhPa         50                   
#&gt; z                     6                     isobaricInhPa         100                  
#&gt; z                     6                     isobaricInhPa         150                  
#&gt; z                     6                     isobaricInhPa         200                  
#&gt; z                     6                     isobaricInhPa         250                  
#&gt; z                     6                     isobaricInhPa         300                  
#&gt; z                     6                     isobaricInhPa         400                  
#&gt; z                     6                     isobaricInhPa         500                  
#&gt; z                     6                     isobaricInhPa         600                  
#&gt; z                     6                     isobaricInhPa         700                  
#&gt; z                     6                     isobaricInhPa         800                  
#&gt; z                     6                     isobaricInhPa         850                  
#&gt; z                     6                     isobaricInhPa         900                  
#&gt; z                     6                     isobaricInhPa         925                  
#&gt; z                     6                     isobaricInhPa         950                  
#&gt; z                     6                     isobaricInhPa         1000                 
#&gt; pres                  1                     heightAboveSea        0                    
#&gt; u                     33                    heightAboveGround     20                   
#&gt; u                     33                    heightAboveGround     50                   
#&gt; u                     33                    heightAboveGround     100                  
#&gt; u                     33                    heightAboveGround     250                  
#&gt; u                     33                    heightAboveGround     500                  
#&gt; u                     33                    heightAboveGround     750                  
#&gt; u                     33                    heightAboveGround     1000                 
#&gt; u                     33                    heightAboveGround     1250                 
#&gt; u                     33                    heightAboveGround     1500                 
#&gt; u                     33                    heightAboveGround     2000                 
#&gt; u                     33                    heightAboveGround     2500                 
#&gt; u                     33                    heightAboveGround     3000                 
#&gt; v                     34                    heightAboveGround     20                   
#&gt; v                     34                    heightAboveGround     50                   
#&gt; v                     34                    heightAboveGround     100                  
#&gt; v                     34                    heightAboveGround     250                  
#&gt; v                     34                    heightAboveGround     500                  
#&gt; v                     34                    heightAboveGround     750                  
#&gt; v                     34                    heightAboveGround     1000                 
#&gt; v                     34                    heightAboveGround     1250                 
#&gt; v                     34                    heightAboveGround     1500                 
#&gt; v                     34                    heightAboveGround     2000                 
#&gt; v                     34                    heightAboveGround     2500                 
#&gt; v                     34                    heightAboveGround     3000                 
#&gt; t                     11                    heightAboveGround     20                   
#&gt; t                     11                    heightAboveGround     50                   
#&gt; t                     11                    heightAboveGround     100                  
#&gt; t                     11                    heightAboveGround     250                  
#&gt; t                     11                    heightAboveGround     500                  
#&gt; t                     11                    heightAboveGround     750                  
#&gt; t                     11                    heightAboveGround     1000                 
#&gt; t                     11                    heightAboveGround     1250                 
#&gt; t                     11                    heightAboveGround     1500                 
#&gt; t                     11                    heightAboveGround     2000                 
#&gt; t                     11                    heightAboveGround     2500                 
#&gt; t                     11                    heightAboveGround     3000                 
#&gt; pres                  1                     heightAboveGround     20                   
#&gt; pres                  1                     heightAboveGround     50                   
#&gt; pres                  1                     heightAboveGround     100                  
#&gt; pres                  1                     heightAboveGround     250                  
#&gt; pres                  1                     heightAboveGround     500                  
#&gt; pres                  1                     heightAboveGround     750                  
#&gt; pres                  1                     heightAboveGround     1000                 
#&gt; pres                  1                     heightAboveGround     1250                 
#&gt; pres                  1                     heightAboveGround     1500                 
#&gt; pres                  1                     heightAboveGround     2000                 
#&gt; pres                  1                     heightAboveGround     2500                 
#&gt; pres                  1                     heightAboveGround     3000                 
#&gt; pres                  1                     heightAboveGround     0                    
#&gt; u                     33                    potentialVorticity    1500                 
#&gt; u                     33                    potentialVorticity    2000                 
#&gt; v                     34                    potentialVorticity    1500                 
#&gt; v                     34                    potentialVorticity    2000                 
#&gt; z                     6                     potentialVorticity    1500                 
#&gt; z                     6                     potentialVorticity    2000                 
#&gt; t                     11                    hybrid                65                   
#&gt; ws                    32                    heightAboveGround     10                   
#&gt; tp                    61                    heightAboveGround     0</code></pre>
<div id="setting-the-shortname" class="section level3">
<h3 class="hasAnchor">
<a href="#setting-the-shortname" class="anchor"></a>Setting the shortName</h3>
<p>If we take for example the grib message with shortName “tp”, we can read this without problem using the harp parameter “Pcp”:</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(<span class="no">grib_file</span>, <span class="st">"Pcp"</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; eidb : TP Total precipitation kg m**-2 
#&gt; Time:
#&gt;  2018/07/10 00:00
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 0 0.2287102 0.5398808 1.363777 1.41673 32.08449</code></pre>
<p>However, what if for some reason we wanted to use “Precip” instead of “Pcp” for the parameter name. Then <code><a href="../reference/read_grid.html">read_grid()</a></code> will not know which <em>shortName</em> to search for, so will attempt to find a message with <em>shortName</em> = “precip”, and won’t be able to find anything. Note it also uses <em>levelType</em> = 255 and <em>level</em> = -999. This means that if it does find messages with with <em>shortName</em> = “precip”, it will ignore the type of level and read messages for all levels.</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(<span class="no">grib_file</span>, <span class="st">"Precip"</span>)</pre></body></html></div>
<pre><code>#&gt; Warning: Parameter "Precip" (shortName: "precip", levelType: "255" for level(s)
#&gt; -999) not found in grib file.</code></pre>
<pre><code>#&gt; Error: None of the requested data could be read from grib file: fc2018071000+006grib_fp</code></pre>
<p>We can then use <code><a href="../reference/grib_opts.html">grib_opts()</a></code> with the argument <code>param_find</code> to force it to look for the <em>shortName</em> “tp” instead. <code>param_find</code> must be a named list with the name being the same as the parameter that is requested, and the elements can be set using a <code>use_grib_*()</code> function, which are listed in the help for <code><a href="../reference/grib_opts.html">grib_opts()</a></code>. To set the grib <em>shortName</em> to look for, we use the <code><a href="../reference/grib_opts.html">use_grib_shortName()</a></code> function.</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="st">"Precip"</span>,
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">param_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw">Precip</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_shortName</a></span>(<span class="st">"tp"</span>))
  )
)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; eidb : TP Total precipitation kg m**-2 
#&gt; Time:
#&gt;  2018/07/10 00:00
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 0 0.2287102 0.5398808 1.363777 1.41673 32.08449</code></pre>
<p>We can also read more than one variable in this way - for example, let’s say we want to read 2m temperature, precipitation and total cloud cover - we will stick with the harp name, “T2m”, for 2m temperature but use different names for precipitation (Precip, <em>shortName</em> = “tp”) and total cloud cover (Cloud, <em>shortName</em> = “tcc”).</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"Cloud"</span>, <span class="st">"T2m"</span>, <span class="st">"Precip"</span>),
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">param_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">Precip</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_shortName</a></span>(<span class="st">"tp"</span>),
      <span class="kw">Cloud</span>  <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_shortName</a></span>(<span class="st">"tcc"</span>)
    )
  )
)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; [[1]]
#&gt; eidb : TCC Total cloud cover  
#&gt; Time:
#&gt;  2018/07/10 00:00 +6
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 0 1 1 0.967729 1 1 
#&gt; 
#&gt; [[2]]
#&gt; eidb : T Temperature K 
#&gt; Time:
#&gt;  2018/07/10 00:00 +6
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 270.9023 275.0146 276.2607 276.3331 278.0359 279.9814 
#&gt; 
#&gt; [[3]]
#&gt; eidb : TP Total precipitation kg m**-2 
#&gt; Time:
#&gt;  2018/07/10 00:00
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 0 0.2287102 0.5398808 1.363777 1.41673 32.08449 
#&gt; 
#&gt; attr(,"class")
#&gt; [1] "geolist" "list"</code></pre>
<p>And if we set the output of <code><a href="../reference/read_grid.html">read_grid()</a></code> to be a data frame, we can see that the modified parameter names have been used.</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"Cloud"</span>, <span class="st">"T2m"</span>, <span class="st">"Precip"</span>),
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">param_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">Precip</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_shortName</a></span>(<span class="st">"tp"</span>),
      <span class="kw">Cloud</span>  <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_shortName</a></span>(<span class="st">"tcc"</span>)
    )
  ),
  <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>), -<span class="no">members</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; # A tibble: 3 x 6
#&gt;   lead_time parameter level_type level units    gridded_data          
#&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;    &lt;geolist&gt;             
#&gt; 1         6 Cloud     unknown        0 fraction &lt;geofield [100 × 100]&gt;
#&gt; 2         6 T2m       height         2 K        &lt;geofield [100 × 100]&gt;
#&gt; 3         6 Precip    unknown        0 kg m**-2 &lt;geofield [100 × 100]&gt;</code></pre>
</div>
<div id="dealing-with-an-unknown-shortname" class="section level3">
<h3 class="hasAnchor">
<a href="#dealing-with-an-unknown-shortname" class="anchor"></a>Dealing with an unknown shortName</h3>
<p>In some cases the grib lookup table that is used may be a local version that is not included with ecCodes. In this case you would need to use another grib key to locate the correct message. Typically this would be <em>indicatorOfParameter</em> for grib edition 1, or <em>paramId</em> for grib edition 2. Looking back to the output of <code>grib_ls</code> above, we can see that the message for total precipitation (<em>shortName</em> = “tp”) has <em>indicatorOfParameter</em> = 61, and that for 10m wind speed (<em>shortName</em> = “ws”) has <em>indicatorOfParameter</em> = 32. We can therefore use these to extract the data from the file by using <code>use_grib_indicatorOfParameter</code>.</p>
<div class="sourceCode" id="cb20"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"total_precipitation"</span>, <span class="st">"wind_speed"</span>),
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">param_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">total_precipitation</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_indicatorOfParameter</a></span>(<span class="fl">61</span>),
      <span class="kw">wind_speed</span>          <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_indicatorOfParameter</a></span>(<span class="fl">32</span>)
    )
  )
)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; [[1]]
#&gt; eidb : TP Total precipitation kg m**-2 
#&gt; Time:
#&gt;  2018/07/10 00:00
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 0 0.2287102 0.5398808 1.363777 1.41673 32.08449 
#&gt; 
#&gt; [[2]]
#&gt; eidb : WS Wind speed m s**-1 
#&gt; Time:
#&gt;  2018/07/10 00:00 +6
#&gt; Domain summary:
#&gt; 100 x 100 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 23.30197 , 78.26077 )
#&gt; SW = ( 8.042 , 77.968 )
#&gt; Data summary:
#&gt; 0.8007516 8.59594 9.882511 9.961892 11.2704 21.45795 
#&gt; 
#&gt; attr(,"class")
#&gt; [1] "geolist" "list"</code></pre>
<p>In practical situations, where the grib <em>shortName</em> is not known, it is the user’s responsibility to know which <em>indicatorOfParameter</em> or <em>paramId</em> to use.</p>
</div>
<div id="reading-data-from-specific-level-types" class="section level3">
<h3 class="hasAnchor">
<a href="#reading-data-from-specific-level-types" class="anchor"></a>Reading data from specific level types</h3>
<p>In our example data file, some data exist on potential vorticity levels. {harpIO} does not know how to read these data, but we can use the <code>level_find</code> argument of <code><a href="../reference/grib_opts.html">grib_opts()</a></code> to select the correct type of level. <code>level_find</code> works in the same way as <code>param_find</code> in that it requires a named list and a <code>use_grib_*()</code> function to set the correct grib keys. Here, the <em>typeOfLevel</em> key has a value of “potentialVorticity”, so we can read the geopotential (Z), wind speed in the x direction of the model grid (U), and wind speed in the y direction of the model grid (V) by setting the <em>typeOfLevel</em> key to “potentialVorticity”. Z, U, V are parameters that {harpIO} knows, so we don’t need to worry about <code>param_find</code>.</p>
<div class="sourceCode" id="cb23"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"U"</span>, <span class="st">"V"</span>, <span class="st">"Z"</span>),
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">level_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">U</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_typeOfLevel</a></span>(<span class="st">"potentialVorticity"</span>),
      <span class="kw">V</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_typeOfLevel</a></span>(<span class="st">"potentialVorticity"</span>),
      <span class="kw">Z</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_typeOfLevel</a></span>(<span class="st">"potentialVorticity"</span>)
    )
  ),
  <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>), -<span class="no">members</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; # A tibble: 6 x 6
#&gt;   lead_time parameter level_type level units      gridded_data          
#&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;      &lt;geolist&gt;             
#&gt; 1         6 U         unknown     1500 m/s        &lt;geofield [100 × 100]&gt;
#&gt; 2         6 U         unknown     2000 m/s        &lt;geofield [100 × 100]&gt;
#&gt; 3         6 V         unknown     1500 m/s        &lt;geofield [100 × 100]&gt;
#&gt; 4         6 V         unknown     2000 m/s        &lt;geofield [100 × 100]&gt;
#&gt; 5         6 Z         unknown     1500 m**2 s**-2 &lt;geofield [100 × 100]&gt;
#&gt; 6         6 Z         unknown     2000 m**2 s**-2 &lt;geofield [100 × 100]&gt;</code></pre>
<p>By default, all levels are read, but we can use the second argument of <code>use_grib_typeOfLevel</code> to set the levels to read:</p>
<div class="sourceCode" id="cb26"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"U"</span>, <span class="st">"V"</span>, <span class="st">"Z"</span>),
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">level_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">U</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_typeOfLevel</a></span>(<span class="st">"potentialVorticity"</span>, <span class="fl">1500</span>),
      <span class="kw">V</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_typeOfLevel</a></span>(<span class="st">"potentialVorticity"</span>, <span class="fl">3000</span>),
      <span class="kw">Z</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_typeOfLevel</a></span>(<span class="st">"potentialVorticity"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2000</span>, <span class="fl">3000</span>))
    )
  ),
  <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>), -<span class="no">members</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; Warning: Parameter "V" (shortName: "v", typeOfLevel: "potentialVorticity" for
#&gt; level(s) 3000) not found in grib file.</code></pre>
<pre><code>#&gt; # A tibble: 2 x 6
#&gt;   lead_time parameter level_type level units      gridded_data          
#&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;      &lt;geolist&gt;             
#&gt; 1         6 U         unknown     1500 m/s        &lt;geofield [100 × 100]&gt;
#&gt; 2         6 Z         unknown     2000 m**2 s**-2 &lt;geofield [100 × 100]&gt;</code></pre>
<p>Note that currently a warning is only given if no levels are found. If more than one level is asked for, but at least one is found the function is silent about the missing levels.</p>
</div>
<div id="reading-specific-levels" class="section level3">
<h3 class="hasAnchor">
<a href="#reading-specific-levels" class="anchor"></a>Reading specific levels</h3>
<p>Currently <code><a href="../reference/read_grid.html">read_grid()</a></code> and <code><a href="../reference/read_forecast.html">read_forecast()</a></code> can either read one or all vertical levels from files. To read a small selection of levels from a grib file, the <code>level_find</code> argument to <code><a href="../reference/grib_opts.html">grib_opts()</a></code> can be used conjunction with <code><a href="../reference/grib_opts.html">use_grib_pressure()</a></code>, <code><a href="../reference/grib_opts.html">use_grib_model()</a></code> and <code><a href="../reference/grib_opts.html">use_grib_heightAboveGround()</a></code> to read from specific pressure, model (hybrid), or height levels. Our example data contain data on a range of pressure levels, so if we want, for example, temperature at 850-, 500- and 200 hPa, we would do the following:</p>
<div class="sourceCode" id="cb30"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="st">"T"</span>,
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">level_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">T</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_pressure</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">850</span>, <span class="fl">500</span>, <span class="fl">200</span>))
    )
  ),
  <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>), -<span class="no">members</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; # A tibble: 3 x 6
#&gt;   lead_time parameter level_type level units gridded_data          
#&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;int&gt; &lt;chr&gt; &lt;geolist&gt;             
#&gt; 1         6 T         pressure     200 K     &lt;geofield [100 × 100]&gt;
#&gt; 2         6 T         pressure     500 K     &lt;geofield [100 × 100]&gt;
#&gt; 3         6 T         pressure     850 K     &lt;geofield [100 × 100]&gt;</code></pre>
<p>Similarly, to read temperature at 500-, 1000- and 1500m above the ground we would do the following:</p>
<div class="sourceCode" id="cb33"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">grib_file</span>,
  <span class="st">"T"</span>,
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">grib_opts</a></span>(
    <span class="kw">level_find</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(
      <span class="kw">T</span> <span class="kw">=</span> <span class="fu"><a href="../reference/grib_opts.html">use_grib_heightAboveGround</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">500</span>, <span class="fl">1000</span>, <span class="fl">1500</span>))
    )
  ),
  <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>), -<span class="no">members</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000+006grib_fp</code></pre>
<pre><code>#&gt; # A tibble: 3 x 6
#&gt;   lead_time parameter level_type level units gridded_data          
#&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;int&gt; &lt;chr&gt; &lt;geolist&gt;             
#&gt; 1         6 T         height       500 K     &lt;geofield [100 × 100]&gt;
#&gt; 2         6 T         height      1000 K     &lt;geofield [100 × 100]&gt;
#&gt; 3         6 T         height      1500 K     &lt;geofield [100 × 100]&gt;</code></pre>
<p>It should be emphasised that <strong>no interpolation is done</strong>. i.e. you can only use <code>level_find</code> to select vertical levels that exist in the file.</p>
</div>
</div>
<div id="netcdf-files" class="section level2">
<h2 class="hasAnchor">
<a href="#netcdf-files" class="anchor"></a>Netcdf files</h2>
<p>Netcdf files are becoming increasingly used in meteorology and climatology. Each variable in a netcdf file is stored as an array that can be subsetted. Each array in the file has attributes and dimensions that describe the variable. In order to read data from netcdf files using {harpIO} it is important that you know something about the contents of the files so that the correct variables can be read and the correct subsets taken. This is done by passing a list generated by the <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> function to <code><a href="../reference/read_forecast.html">read_forecast()</a></code> or <code><a href="../reference/read_grid.html">read_grid()</a></code> via the <code>file_format_opts</code> argument. <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> generates a list that has names for the dimensions of an array and either where to find the geographic projection information in the file, or the projection information as a <a href="https://proj.org/operations/projections/index.html">proj4 string</a>, and whether any of the dimensions are reversed.</p>
<p>We can use a netcdf file from the {harpData} package to show how <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> works.</p>
<div class="sourceCode" id="cb36"><html><body><pre class="r"><span class="no">nc_file</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/system.file.html">system.file</a></span>(
  <span class="st">"netcdf/AAEPS/fc2018071000.nc"</span>,
  <span class="kw">package</span> <span class="kw">=</span> <span class="st">"harpData"</span>
)</pre></body></html></div>
<p>Then we can open a connection to the file using the {ncdf4} package to get a summary of the contents of the file.</p>
<div class="sourceCode" id="cb37"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ncdf4</span>)
<span class="no">nc</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ncdf4/man/nc_open.html">nc_open</a></span>(<span class="no">nc_file</span>)
<span class="no">nc</span></pre></body></html></div>
<pre><code>#&gt; File fc2018071000.nc (NC_FORMAT_NETCDF4_CLASSIC):
#&gt; 
#&gt;      13 variables (excluding dimension variables):
#&gt;         double forecast_reference_time[]   
#&gt;             units: seconds since 1970-01-01 00:00:00 +00:00
#&gt;             standard_name: forecast_reference_time
#&gt;         double p0[]   
#&gt;             units: Pa
#&gt;         double ap[hybrid]   
#&gt;             units: Pa
#&gt;         double b[hybrid]   
#&gt;             units: 1
#&gt;         int projection_lambert[]   
#&gt;             grid_mapping_name: lambert_conformal_conic
#&gt;             standard_parallel: 77.5
#&gt;              standard_parallel: 77.5
#&gt;             longitude_of_central_meridian: -25
#&gt;             latitude_of_projection_origin: 77.5
#&gt;             earth_radius: 6371000
#&gt;             proj4: +proj=lcc +lat_0=77.5 +lon_0=-25 +lat_1=77.5 +lat_2=77.5 +no_defs +R=6.371e+06
#&gt;         double longitude[x,y]   
#&gt;             units: degree_east
#&gt;             long_name: longitude
#&gt;             standard_name: longitude
#&gt;         double latitude[x,y]   
#&gt;             units: degree_north
#&gt;             long_name: latitude
#&gt;             standard_name: latitude
#&gt;         int specific_humidity_ml[x,y,ensemble_member,hybrid,time]   
#&gt;             _FillValue: -2147483647
#&gt;             long_name: Specific humidity model levels
#&gt;             standard_name: specific_humidity
#&gt;             units: kg/kg
#&gt;             grid_mapping: projection_lambert
#&gt;             coordinates: longitude latitude
#&gt;             scale_factor: 1e-07
#&gt;         float air_temperature_2m[x,y,ensemble_member,height1,time]   
#&gt;             _FillValue: 9.96920996838687e+36
#&gt;             long_name: Screen level temperature (T2M)
#&gt;             standard_name: air_temperature
#&gt;             units: K
#&gt;             grid_mapping: projection_lambert
#&gt;             coordinates: longitude latitude
#&gt;         float specific_humidity_2m[x,y,ensemble_member,height1,time]   
#&gt;             _FillValue: 9.96920996838687e+36
#&gt;             long_name: Screen level specific humidity
#&gt;             standard_name: specific_humidity
#&gt;             units: kg/kg
#&gt;             grid_mapping: projection_lambert
#&gt;             coordinates: longitude latitude
#&gt;         int air_temperature_ml[x,y,ensemble_member,hybrid,time]   
#&gt;             _FillValue: -2147483647
#&gt;             long_name: Air temperature model levels
#&gt;             standard_name: air_temperature
#&gt;             units: K
#&gt;             grid_mapping: projection_lambert
#&gt;             coordinates: longitude latitude
#&gt;             scale_factor: 0.001
#&gt;         float surface_air_pressure[x,y,ensemble_member,height0,time]   
#&gt;             _FillValue: 9.96920996838687e+36
#&gt;             long_name: Surface air pressure
#&gt;             standard_name: surface_air_pressure
#&gt;             units: Pa
#&gt;             grid_mapping: projection_lambert
#&gt;             coordinates: longitude latitude
#&gt;         float surface_geopotential[x,y,ensemble_member,height0,time]   
#&gt;             _FillValue: 9.96920996838687e+36
#&gt;             long_name: Surface geopotential (fis)
#&gt;             standard_name: surface_geopotential
#&gt;             units: m^2/s^2
#&gt;             grid_mapping: projection_lambert
#&gt;             coordinates: longitude latitude
#&gt; 
#&gt;      7 dimensions:
#&gt;         time  Size:5   *** is unlimited ***
#&gt;             long_name: time
#&gt;             standard_name: time
#&gt;             units: seconds since 1970-01-01 00:00:00 +00:00
#&gt;         ensemble_member  Size:5
#&gt;             long_name: ensemble run number
#&gt;             standard_name: realization
#&gt;             flag_values: 0
#&gt;              flag_values: 1
#&gt;              flag_values: 2
#&gt;              flag_values: 3
#&gt;              flag_values: 4
#&gt;              flag_values: 5
#&gt;              flag_values: 6
#&gt;              flag_values: 7
#&gt;              flag_values: 8
#&gt;              flag_values: 9
#&gt;              flag_values: 10
#&gt;             flag_meanings: mbr000 mbr001 mbr002 mbr003 mbr004 mbr005 mbr006 mbr007 mbr008 mbr009 mbr010
#&gt;         height0  Size:1
#&gt;             description: height above ground
#&gt;             long_name: height
#&gt;             positive: up
#&gt;             units: m
#&gt;         height1  Size:1
#&gt;             description: height above ground
#&gt;             long_name: height
#&gt;             positive: up
#&gt;             units: m
#&gt;         hybrid  Size:65
#&gt;             standard_name: atmosphere_hybrid_sigma_pressure_coordinate
#&gt;             formula: p(n,k,j,i) = ap(k) + b(k)*ps(n,j,i)
#&gt;             formula_terms: ap: ap b: b ps: surface_air_pressure p0: p0
#&gt;             long_name: atmosphere_hybrid_sigma_pressure_coordinate
#&gt;             positive: down
#&gt;         x  Size:100
#&gt;             long_name: x-coordinate in Cartesian system
#&gt;             standard_name: projection_x_coordinate
#&gt;             units: m
#&gt;         y  Size:100
#&gt;             long_name: y-coordinate in Cartesian system
#&gt;             standard_name: projection_y_coordinate
#&gt;             units: m
#&gt; 
#&gt;     16 global attributes:
#&gt;         Conventions: CF-1.6
#&gt;         institution: Norwegian Meteorological Institute, MET Norway
#&gt;         creator_url: met.no
#&gt;         summary: MEPS (MetCoOp-Ensemble Prediction System) is a convection-permitting atmosphere ensemble model covering Scandinavia and the Nordic Seas. It has horizontal resolution of 2.5 km, has 65 vertical levels and 10 members. MEPS is ran four times daily (00,06,12,18) with three-hourly cycling for data assimilation. Member 0 and 1 are ran up to 66 hours, the rest up to 48 hours. Boundary data is from ECMWF, and initial perturbations are based on the SLAF method. Model code based on HARMONIE cy40h1.1
#&gt;         source: MEPS 2.5km
#&gt;         title: MEPS 2.5km
#&gt;         min_time: 2018-07-10 00:00:00Z
#&gt;         max_time: 2018-07-12
#&gt;         geospatial_lat_min: 51.0
#&gt;         geospatial_lat_max: 88.0
#&gt;         geospatial_lon_min: -20.0
#&gt;         geospatial_lon_max: 80.0
#&gt;         references: unknown
#&gt;         license: https://www.met.no/en/free-meteorological-data/Licensing-and-crediting
#&gt;         comment: none
#&gt;         history: 2019-07-17 creation by fimex</code></pre>
<p>From the above you see the variables, their attributes, the dimensions of the variables and some global attributes. We can use this information to set the correct information using <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> when we want to read data using <code><a href="../reference/read_forecast.html">read_forecast()</a></code>, or <code><a href="../reference/read_grid.html">read_grid()</a></code>. For these examples we will use <code><a href="../reference/read_grid.html">read_grid()</a></code>, but the same principles apply for <code><a href="../reference/read_forecast.html">read_forecast()</a></code>.</p>
<p>It is important to close the connection to a netcdf file when we are finished with it (this is taken care of for us when we use <code><a href="../reference/read_forecast.html">read_forecast()</a></code> and <code><a href="../reference/read_grid.html">read_grid()</a></code>).</p>
<div class="sourceCode" id="cb39"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/pkg/ncdf4/man/nc_close.html">nc_close</a></span>(<span class="no">nc</span>)</pre></body></html></div>
<p>Let’s take a look at some of the default values for <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code></p>
<div class="sourceCode" id="cb40"><html><body><pre class="r"><span class="fu"><a href="../reference/netcdf_opts.html">netcdf_opts</a></span>()</pre></body></html></div>
<pre><code>#&gt; $options_set
#&gt; [1] "none"
#&gt; 
#&gt; $proj4_var
#&gt; [1] "projection_lambert"
#&gt; 
#&gt; $proj4_att
#&gt; [1] "proj4"
#&gt; 
#&gt; $proj4
#&gt; NULL
#&gt; 
#&gt; $x_dim
#&gt; [1] "x"
#&gt; 
#&gt; $y_dim
#&gt; [1] "y"
#&gt; 
#&gt; $lon_var
#&gt; [1] "longitude"
#&gt; 
#&gt; $lat_var
#&gt; [1] "latitude"
#&gt; 
#&gt; $x_rev
#&gt; [1] FALSE
#&gt; 
#&gt; $y_rev
#&gt; [1] FALSE
#&gt; 
#&gt; $z_var
#&gt; [1] NA
#&gt; 
#&gt; $member_var
#&gt; [1] NA
#&gt; 
#&gt; $time_var
#&gt; [1] "time"
#&gt; 
#&gt; $ref_time_var
#&gt; [1] NA</code></pre>
<div id="projection-information" class="section level3">
<h3 class="hasAnchor">
<a href="#projection-information" class="anchor"></a>Projection information</h3>
<p>There are 3 elements in the list that begin with <code>proj4_</code>. These are to control where the projection information is obtained.</p>
<ul>
<li>
<em>proj4_var</em> is the name of the variable in the netcdf file that holds the proj4 string.</li>
<li>
<em>proj4_att</em> is the name of the attribute of <em>proj4_var</em> that has the proj4 string. If set to <code>NULL</code>, an attempt is made to read the proj4 string directly from <em>proj4_var</em>
</li>
<li>
<em>proj4</em> is where you can set the proj4 string directly rather than attempt to read it from the file. If <em>proj4</em> is not <code>NULL</code>, <em>proj4_var</em> and <em>proj4_att</em> are ignored.</li>
</ul>
<p>In the summary of our netcdf file above, there is a variable <code>projection_lambert</code> that has an attribute <code>proj4</code>, which contains the proj4 string “+proj=lcc +lat_0=77.5 +lon_0=-25 +lat_1=77.5 +lat_2=77.5 +no_defs +R=6.371e+06”, so the default values we get from <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> are correct for this file.</p>
</div>
<div id="dimension-names" class="section level3">
<h3 class="hasAnchor">
<a href="#dimension-names" class="anchor"></a>Dimension names</h3>
<p>The dimension names of variables are set using <em>x_dim</em>, <em>y_dim</em>, <em>z_var</em>, <em>member_var</em> and <em>time_var</em>. The reason we need to know the names are that arrays in netcdf file can be stored in any dimension order, and we may wish to read only a subset of the array so we need to know which parts of the dimensions to take. By default, <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> gives us:</p>
<div class="sourceCode" id="cb42"><html><body><pre class="r"><span class="no">x_dim</span>      <span class="kw">=</span> <span class="st">"x"</span>
<span class="no">y_dim</span>      <span class="kw">=</span> <span class="st">"y"</span>
<span class="no">time_var</span>   <span class="kw">=</span> <span class="st">"time"</span>
<span class="no">z_var</span>      <span class="kw">=</span> <span class="fl">NA</span>
<span class="no">member_var</span> <span class="kw">=</span> <span class="fl">NA</span></pre></body></html></div>
<p>Since <em>z_var</em> and <em>member_var</em> are NA, the default means that it is expecting to find variables in the netcdf file with 3 dimensions: “x”, “y” and “time”. If we go back to our example above, and let’s say we want to read 2m temperature (“air_temperature_2m”, or the harp parameter “T2m”), we see that air_temperature_2m has 5 dimensions: <em>x</em>, <em>y</em>, <em>ensemble_member</em>, <em>height1</em> and <em>time</em>. We therefore need to modify the values of <em>z_var</em> and <em>member_var</em> using <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code>:</p>
<div class="sourceCode" id="cb43"><html><body><pre class="r"><span class="no">my_nc_opts</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/netcdf_opts.html">netcdf_opts</a></span>(<span class="kw">z_var</span> <span class="kw">=</span> <span class="st">"height1"</span>, <span class="kw">member_var</span> <span class="kw">=</span> <span class="st">"ensemble_member"</span>)</pre></body></html></div>
</div>
<div id="latitude-longitude-and-time" class="section level3">
<h3 class="hasAnchor">
<a href="#latitude-longitude-and-time" class="anchor"></a>Latitude, longitude and time</h3>
<p>This leaves <em>lon_var</em>, <em>lat_var</em> and <em>ref_time_var</em>. If the file contains arrays of longitude and latitude, these are used to geographically orientate the data - if they are set to <code>NULL</code> an attempt is made to do this using <em>x_dim</em> and <em>y_dim</em> and the projection information. <em>ref_time_var</em> is used in forecasts to calculate the lead time. If set to NA, the lead time is calculated by subtracting the first element of the time dimension from each subsequent element.</p>
<p>We can now attempt to read some data - firstly without using <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code>:</p>
<div class="sourceCode" id="cb44"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(<span class="no">nc_file</span>, <span class="st">"T2m"</span>, <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000.nc</code></pre>
<pre><code>#&gt; Warning: No 'format_opts' passed for NetCDF file. Using default netcdf_opts()</code></pre>
<pre><code>#&gt; Warning: Requested dimensions do not match for 'T2m' in fc2018071000.nc.
#&gt; Requested dimensions: (time, x, y)
#&gt; Dimensions in file: (ensemble_member, height1, time, x, y).</code></pre>
<pre><code>#&gt; Error: Cannot read from netcdf file: fc2018071000.nc</code></pre>
<p>The error tells you what dimension names you have given - in this case (time, x, y) - the defaults from <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code>, and what dimensions it found in the file: (ensemble_member, height1, time, x, y). Note that in the warning the dimensions are listed in alphabetical order, it us up to you to decide which dimension they should go with.</p>
<p>So, now if we use our modified options to read the file, we should get a result:</p>
<div class="sourceCode" id="cb49"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(<span class="no">nc_file</span>, <span class="st">"T2m"</span>, <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="no">my_nc_opts</span>, <span class="kw">data_frame</span> <span class="kw">=</span> <span class="fl">TRUE</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>))</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000.nc</code></pre>
<pre><code>#&gt; # A tibble: 25 x 7
#&gt;    lead_time parameter level_type level units gridded_data           members
#&gt;        &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;geolist&gt;                &lt;int&gt;
#&gt;  1         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       0
#&gt;  2         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       1
#&gt;  3         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       2
#&gt;  4         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       3
#&gt;  5         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       4
#&gt;  6         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       0
#&gt;  7         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       1
#&gt;  8         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       2
#&gt;  9         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       3
#&gt; 10         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       4
#&gt; # … with 15 more rows</code></pre>
<p>We can also select specific members and lead times:</p>
<div class="sourceCode" id="cb52"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">nc_file</span>,
  <span class="st">"T2m"</span>,
  <span class="kw">lead_time</span>        <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">3</span>),
  <span class="kw">members</span>          <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fl">2</span>, <span class="fl">4</span>),
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="no">my_nc_opts</span>,
  <span class="kw">data_frame</span>       <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>))</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000.nc</code></pre>
<pre><code>#&gt; # A tibble: 6 x 7
#&gt;   lead_time parameter level_type level units gridded_data           members
#&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;geolist&gt;                &lt;int&gt;
#&gt; 1         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       0
#&gt; 2         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       2
#&gt; 3         0 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       4
#&gt; 4         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       0
#&gt; 5         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       2
#&gt; 6         3 T2m       height         2 K     &lt;geofield [100 × 100]&gt;       4</code></pre>
</div>
<div id="options-sets" class="section level3">
<h3 class="hasAnchor">
<a href="#options-sets" class="anchor"></a>Options sets</h3>
<p>Finally, <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> has a number of default sets of options that can be set via the <code>options_set</code> argument. These set the options to known values for some data sources - currently operational NWP forecasts from MET Norway and WRF (though this isn’t fully tested). These options are:</p>
<ul>
<li>“met_norway_eps” - EPS forecasts produced by MET Norway,</li>
<li>“met_norway_det” - deterministic forecasts produced by MET Norway</li>
<li>“met_norway_ifsens” - IFSENS forecasts from ECMWF archived at MET Norway</li>
<li>“met_norway_ifshires” - IFSHIRES forecasts from ECMWF archived at MET Norway</li>
<li>“wrf” - WRF forecasts on the WRF “mass” grid</li>
<li>“wrf_u_stagger” - WRF forecasts on the U-staggered grid</li>
<li>“wrf_v_stagger” - WRF forecasts on the V-staggered grid</li>
</ul>
<p>You can, for example, use the “met_norway_det” options set when reading data from the MET Norway thredds server:</p>
<div class="sourceCode" id="cb55"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="st">"https://thredds.met.no/thredds/dodsC/aromearcticarchive/2021/03/01/arome_arctic_extracted_2_5km_20210301T21Z.nc"</span>,
  <span class="st">"T2m"</span>,
  <span class="kw">lead_time</span>        <span class="kw">=</span> <span class="fl">6</span>,
  <span class="kw">file_format</span>      <span class="kw">=</span> <span class="st">"netcdf"</span>,
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/netcdf_opts.html">netcdf_opts</a></span>(<span class="st">"met_norway_det"</span>)
)</pre></body></html></div>
<pre><code>#&gt; Reading https://thredds.met.no/thredds/dodsC/aromearcticarchive/2021/03/01/arome_arctic_extracted_2_5km_20210301T21Z.nc</code></pre>
<pre><code>#&gt;  : T2m K 
#&gt; Time:
#&gt;  2021/03/01 21:00
#&gt; Domain summary:
#&gt; 739 x 949 domain
#&gt; Projection summary:
#&gt; proj= lcc 
#&gt; NE = ( 68.83323 , 71.10861 )
#&gt; SW = ( -17.957 , 69.299 )
#&gt; Data summary:
#&gt; 241.2239 257.6566 267.764 264.93 272.1761 279.136</code></pre>
<p>Note that to download data from an external source we need to explicitly tell <code><a href="../reference/read_grid.html">read_grid()</a></code> (or <code><a href="../reference/read_forecast.html">read_forecast()</a></code>) that the file format is “netcdf”. This is because when the file is on disk an initial scan of the file is done to try and guess the format, but this is not possible with external files. For demonstration purposes we could do the same using <code><a href="../reference/read_forecast.html">read_forecast()</a></code></p>
<div class="sourceCode" id="cb58"><html><body><pre class="r"><span class="no">url</span>      <span class="kw">&lt;-</span> <span class="st">"https://thredds.met.no/thredds/dodsC/aromearcticarchive"</span>
<span class="no">template</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(
  <span class="st">"{YYYY}/{MM}/{DD}/"</span>,
  <span class="st">"{fcst_model}_extracted_2_5km_{YYYY}{MM}{DD}T{HH}Z.nc"</span>
)
<span class="fu"><a href="../reference/read_forecast.html">read_forecast</a></span>(
  <span class="fl">2021030100</span>,
  <span class="fl">2021030118</span>,
  <span class="kw">fcst_model</span>       <span class="kw">=</span> <span class="st">"arome_arctic"</span>,
  <span class="kw">parameter</span>        <span class="kw">=</span> <span class="st">"T2m"</span>,
  <span class="kw">by</span>               <span class="kw">=</span> <span class="st">"6h"</span>,
  <span class="kw">lead_time</span>        <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="fl">0</span>, <span class="fl">3</span>),
  <span class="kw">file_path</span>        <span class="kw">=</span> <span class="no">url</span>,
  <span class="kw">file_template</span>    <span class="kw">=</span> <span class="no">template</span>,
  <span class="kw">file_format</span>      <span class="kw">=</span> <span class="st">"netcdf"</span>,
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="fu"><a href="../reference/netcdf_opts.html">netcdf_opts</a></span>(<span class="st">"met_norway_det"</span>),
  <span class="kw">return_data</span>      <span class="kw">=</span> <span class="fl">TRUE</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">starts_with</a></span>(<span class="st">"level"</span>), -<span class="no">fcst_cycle</span> ,-<span class="no">validdate</span>)</pre></body></html></div>
<pre><code>#&gt; Reading https://thredds.met.no/thredds/dodsC/aromearcticarchive/2021/03/01/arome_arctic_extracted_2_5km_20210301T00Z.nc</code></pre>
<pre><code>#&gt; Reading https://thredds.met.no/thredds/dodsC/aromearcticarchive/2021/03/01/arome_arctic_extracted_2_5km_20210301T06Z.nc</code></pre>
<pre><code>#&gt; Reading https://thredds.met.no/thredds/dodsC/aromearcticarchive/2021/03/01/arome_arctic_extracted_2_5km_20210301T12Z.nc</code></pre>
<pre><code>#&gt; Reading https://thredds.met.no/thredds/dodsC/aromearcticarchive/2021/03/01/arome_arctic_extracted_2_5km_20210301T18Z.nc</code></pre>
<pre><code>#&gt; ● arome_arctic
#&gt; # A tibble: 16 x 5
#&gt;    fcdate              lead_time parameter units arome_arctic_det      
#&gt;    &lt;dttm&gt;                  &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;geolist&gt;             
#&gt;  1 2021-03-01 00:00:00         0 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  2 2021-03-01 00:00:00         1 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  3 2021-03-01 00:00:00         2 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  4 2021-03-01 00:00:00         3 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  5 2021-03-01 06:00:00         0 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  6 2021-03-01 06:00:00         1 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  7 2021-03-01 06:00:00         2 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  8 2021-03-01 06:00:00         3 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt;  9 2021-03-01 12:00:00         0 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 10 2021-03-01 12:00:00         1 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 11 2021-03-01 12:00:00         2 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 12 2021-03-01 12:00:00         3 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 13 2021-03-01 18:00:00         0 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 14 2021-03-01 18:00:00         1 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 15 2021-03-01 18:00:00         2 T2m       K     &lt;geofield [739 × 949]&gt;
#&gt; 16 2021-03-01 18:00:00         3 T2m       K     &lt;geofield [739 × 949]&gt;</code></pre>
</div>
<div id="the-z_var-problem" class="section level3">
<h3 class="hasAnchor">
<a href="#the-z_var-problem" class="anchor"></a>The <em>z_var</em> problem</h3>
<p>Netcdf files typically contain many variables, and for meteorological data they can have a range of vertical coordinates - e.g. height, pressure, model levels etc. So although we have set our options with <code><a href="../reference/netcdf_opts.html">netcdf_opts()</a></code> we don’t want to set everything for every variable we wish to read from the file. To address this, the function <code><a href="../reference/modify_opts.html">modify_opts()</a></code> can be used to change one or more options. If we try to read “specific_humidity_ml” from our example file with the netcdf options we currently have, we will get an error as <em>z_var</em> = “height1”, but for this variable it needs to be “hybrid”:</p>
<div class="sourceCode" id="cb64"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">nc_file</span>,
  <span class="st">"specific_humidity_ml"</span>,
  <span class="kw">lead_time</span>        <span class="kw">=</span> <span class="fl">3</span>,
  <span class="kw">file_format_opts</span> <span class="kw">=</span> <span class="no">my_nc_opts</span>,
  <span class="kw">data_frame</span>       <span class="kw">=</span> <span class="fl">TRUE</span>
)</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000.nc</code></pre>
<pre><code>#&gt; Warning: Requested dimensions do not match for 'specific_humidity_ml' in fc2018071000.nc.
#&gt; Requested dimensions: (ensemble_member, height1, time, x, y)
#&gt; Dimensions in file: (ensemble_member, hybrid, time, x, y).</code></pre>
<pre><code>#&gt; Error: Cannot read from netcdf file: fc2018071000.nc</code></pre>
<p>So, to change <em>z_var</em> to “hybrid” we use <code><a href="../reference/modify_opts.html">modify_opts()</a></code>:</p>
<div class="sourceCode" id="cb68"><html><body><pre class="r"><span class="fu"><a href="../reference/read_grid.html">read_grid</a></span>(
  <span class="no">nc_file</span>,
  <span class="st">"specific_humidity_ml"</span>,
  <span class="kw">lead_time</span>            <span class="kw">=</span> <span class="fl">3</span>,
  <span class="kw">file_format_opts</span>     <span class="kw">=</span> <span class="fu"><a href="../reference/modify_opts.html">modify_opts</a></span>(<span class="no">my_nc_opts</span>, <span class="kw">z_var</span> <span class="kw">=</span> <span class="st">"hybrid"</span>),
  <span class="kw">data_frame</span>           <span class="kw">=</span> <span class="fl">TRUE</span>,
  <span class="kw">vertical_coordinate</span> <span class="kw">=</span> <span class="st">"model"</span>
) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span>(-<span class="fu"><a href="https://dplyr.tidyverse.org/reference/reexports.html">ends_with</a></span>(<span class="st">"date"</span>))</pre></body></html></div>
<pre><code>#&gt; Reading fc2018071000.nc</code></pre>
<pre><code>#&gt; # A tibble: 325 x 7
#&gt;    lead_time parameter        level_type   level units gridded_data      members
#&gt;        &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt; &lt;geolist&gt;           &lt;int&gt;
#&gt;  1         3 specific_humidi… model      0.00987 kg/kg &lt;geofield [100 ×…       0
#&gt;  2         3 specific_humidi… model      0.00987 kg/kg &lt;geofield [100 ×…       1
#&gt;  3         3 specific_humidi… model      0.00987 kg/kg &lt;geofield [100 ×…       2
#&gt;  4         3 specific_humidi… model      0.00987 kg/kg &lt;geofield [100 ×…       3
#&gt;  5         3 specific_humidi… model      0.00987 kg/kg &lt;geofield [100 ×…       4
#&gt;  6         3 specific_humidi… model      0.0296  kg/kg &lt;geofield [100 ×…       0
#&gt;  7         3 specific_humidi… model      0.0296  kg/kg &lt;geofield [100 ×…       1
#&gt;  8         3 specific_humidi… model      0.0296  kg/kg &lt;geofield [100 ×…       2
#&gt;  9         3 specific_humidi… model      0.0296  kg/kg &lt;geofield [100 ×…       3
#&gt; 10         3 specific_humidi… model      0.0296  kg/kg &lt;geofield [100 ×…       4
#&gt; # … with 315 more rows</code></pre>
<p>We also have to pass the <code>vertical_coordinate = "model"</code> to get the correct name in the <code>level_type</code> coloumn in the data frame of the output.</p>
<p>Note that for variables with a singleton z dimension, any name can be given for <em>z_var</em> as long as it exists as a dimension in the file. Furthermore, if there are many different dimensions with names such as “height0”, “height1”, “height2” etc. the number doesn’t have to match. This means that you do not have to modify <em>z_var</em> so much.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Andrew Singleton, Alex Deckmyn.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
